version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(levelname)-5s | %(asctime)s | %(name)s | %(message)s'
    datefmt: "%d/%m/%Y %H:%M:%S"
  error:
    format: "%(levelname)-5s | %(asctime)s | %(name)s.%(funcName)s() | %(message)s"
    datefmt: "%d/%m/%Y %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: "ext://sys.stdout"

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ../logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: ../logs/errors.log
    maxBytes: 10485760
    backupCount: 10
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ../logs/debug.log
    maxBytes: 20485760
    backupCount: 10
    encoding: utf8

loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler, debug_file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console, info_file_handler, error_file_handler, debug_file_handler]
